services:
  - type: web
    name: meeting-prep-backend
    env: python
    region: oregon  # or choose your preferred region
    plan: free  # or specify paid plan if needed
    pythonVersion: 3.9  # specify your Python version
    buildCommand: |
      python -m pip install --upgrade pip
      pip cache purge
      if [ "$(uname)" == "Linux" ]; then
        pip install uvloop
      fi
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 2 --timeout 120
    healthCheckPath: /health  # you'll need to add this endpoint
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
    autoDeploy: true  # enables automatic deployments
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1